version: "3.9"

services:
  tts:
    build: .
    container_name: tts_service
    volumes:
      - ./output:/app/output   # Los audios se guardarán en esta carpeta
    working_dir: /app
    command: ["python", "script.py"]
